package aex

import (
	"context"
	"crypto/md5"
	"encoding/hex"
	"errors"
	"fmt"
	"time"
)

const (
	// authPath is the Authorization Access endpoint that generates access
	// codes. Paths are joined onto a base URL that already ends in a
	// slash, so they carry no leading slash.
	authPath = "autorizacion-acceso/generar"

	// tokenLifetime is how long the AEX API keeps an access code valid.
	tokenLifetime = 10 * time.Minute

	// tokenRefreshMargin is subtracted from tokenLifetime when deciding
	// whether a cached access code is still usable, so a code is never
	// attached to a request that would arrive too close to its expiry.
	tokenRefreshMargin = 2 * time.Minute
)

// hashPrivateKey builds the value the API expects in clave_privada:
// md5(privateKey + sessionCode), hex-encoded.
func hashPrivateKey(privateKey, sessionCode string) string {
	sum := md5.Sum([]byte(privateKey + sessionCode))
	return hex.EncodeToString(sum[:])
}

// authRequest is the payload of the Authorization Access Generate method.
type authRequest struct {
	PublicKey   string `json:"clave_publica"`
	PrivateKey  string `json:"clave_privada"`
	SessionCode string `json:"codigo_sesion"`
}

// AuthResponse is the response of the Authorization Access Generate method.
type AuthResponse struct {
	baseResponse
	// AuthorizationCode (codigo_autorizacion) is the access token for API
	// operations. It is unique, valid for 10 minutes, and null when the
	// credentials are not valid.
	AuthorizationCode string `json:"codigo_autorizacion"`
}

// Authenticate requests a fresh authorization code from the Authorization
// Access service, caching it for subsequent calls. It is not usually
// necessary: every client method obtains and refreshes the code
// automatically. Use it to validate credentials up front or to force a
// refresh. The returned string is the current authorization code.
//
// Failures wrap ErrUnauthorized.
func (c *Client) Authenticate(ctx context.Context) (string, error) {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.generateToken(ctx)
}

// authorizationCode returns a usable authorization code, generating a
// new one when the cached code is missing or close to expiry. The bool
// result reports whether the code was generated by this call (as opposed
// to reused from the cache), which callers use to decide whether an API
// error could be due to a stale code.
func (c *Client) authorizationCode(ctx context.Context) (string, bool, error) {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.cachedToken(ctx)
}

// cachedToken implements token; the caller must hold c.mu.
func (c *Client) cachedToken(ctx context.Context) (code string, fresh bool, err error) {
	if c.token != "" && time.Since(c.tokenAcquiredAt) < tokenLifetime-tokenRefreshMargin {
		return c.token, false, nil
	}
	code, err = c.generateToken(ctx)
	if err != nil {
		return "", false, err
	}
	return code, true, nil
}

// generateToken calls the Authorization Access service and caches the
// resulting code. The caller must hold c.mu.
func (c *Client) generateToken(ctx context.Context) (string, error) {
	req := authRequest{
		PublicKey:   c.config.PublicKey,
		PrivateKey:  hashPrivateKey(c.config.PrivateKey, c.config.SessionCode),
		SessionCode: c.config.SessionCode,
	}

	var resp AuthResponse
	if err := c.doRequest(ctx, authPath, req, &resp); err != nil {
		return "", fmt.Errorf("aex: authenticate: %w", err)
	}
	if err := checkResponse(authPath, resp.baseResponse); err != nil {
		return "", fmt.Errorf("aex: authenticate: %w: %w", ErrUnauthorized, err)
	}
	if resp.AuthorizationCode == "" {
		return "", fmt.Errorf("aex: authenticate: %w: response carried no authorization code", ErrUnauthorized)
	}

	c.token = resp.AuthorizationCode
	c.tokenAcquiredAt = time.Now()
	return c.token, nil
}

// doAuthenticated performs an authenticated POST request against path.
// It injects the public key and a current authorization code into payload
// (which must embed authFields), decodes the response into out, and
// validates the response envelope.
func (c *Client) doAuthenticated(ctx context.Context, path string, payload any, out any) error {
	return c.runAuthenticated(ctx, path, payload, func() error {
		if err := c.doRequest(ctx, path, payload, out); err != nil {
			return err
		}
		return responseError(path, out)
	})
}

// runAuthenticated injects the public key and a current authorization code
// into payload (which must embed authFields) and executes op.
//
// If op reports an API error and the code was reused from the cache, the
// code may have expired server-side before its nominal validity ended; in
// that case runAuthenticated re-authenticates and executes op again
// exactly once. Calls made with a freshly generated code are never
// retried.
func (c *Client) runAuthenticated(ctx context.Context, path string, payload any, op func() error) error {
	code, fresh, err := c.authorizationCode(ctx)
	if err != nil {
		return err
	}

	setRequestCredentials(payload, c.config.PublicKey, code)
	err = op()
	if err == nil {
		return nil
	}

	var apiErr *APIError
	if fresh || !errors.As(err, &apiErr) {
		return err
	}

	code, err = c.Authenticate(ctx)
	if err != nil {
		return err
	}
	setRequestCredentials(payload, c.config.PublicKey, code)
	return op()
}

// setRequestCredentials injects credentials into a request payload that
// embeds authFields. Payloads without credentials are left untouched.
func setRequestCredentials(payload any, publicKey, authorizationCode string) {
	if cred, ok := payload.(credentialedRequest); ok {
		cred.setCredentials(publicKey, authorizationCode)
	}
}
