package aex

import (
	"context"
	"encoding/json"
	"fmt"
)

const requestServicePath = "envios/solicitar_servicio"

// RequestServiceParams are the parameters of the Shipments Request Service
// method. The resulting offer has a validity period agreed with each
// merchant; once it expires without confirmation it is deleted.
type RequestServiceParams struct {
	authFields
	// Origin is the origin city code.
	Origin string `json:"origen"`
	// Destino is the destination city code.
	Destino string `json:"destino"`
	// OperationCode identifies the operation performed in the merchant
	// portal (Order ID).
	OperationCode string `json:"codigo_operacion,omitempty"`
	// Packages is the list of packages to be shipped.
	Packages []Package `json:"paquetes"`
	// LoadType is the cargo type code: LoadPackage ("P", the default) or
	// LoadDocument ("D"). Omitted when empty.
	LoadType string `json:"codigo_tipo_carga,omitempty"`
	// CollectionAmount is the amount used to calculate the cash on
	// delivery commission. When 0, the commission is calculated from the
	// sum of the declared value of the cargo.
	CollectionAmount int `json:"importe_cobro,omitempty"`
}

func (p RequestServiceParams) validate() error {
	if p.Origin == "" {
		return fmt.Errorf("aex: request service: Origin is required")
	}
	if p.Destino == "" {
		return fmt.Errorf("aex: request service: Destino is required")
	}
	if len(p.Packages) == 0 {
		return fmt.Errorf("aex: request service: at least one package is required")
	}
	return nil
}

// ReturnShipment describes a return shipment associated with an additional
// service (devolucion). It is null when the additional service does not
// generate a return.
type ReturnShipment struct {
	// ServiceTypeID is the service type ID to use for the return guide.
	ServiceTypeID FlexInt `json:"id_tipo_servicio"`
	// ServiceType is the service name.
	ServiceType string `json:"tipo_servicio"`
	// Cost is the additional service cost in guaraníes.
	Cost FlexFloat `json:"costo"`
	// LoadType is LoadDocument ("D") when the return corresponds to
	// documents that must be completed and returned to the sender, or
	// LoadPackage ("P") when packages are collected from the delivery
	// location (e.g., exchanges).
	LoadType string `json:"codigo_tipo_carga"`
}

// ConditionAdditional is an additional service attached to a service
// condition, carrying the selection flags described by RequestService.
type ConditionAdditional struct {
	AdditionalService
	// Mandatory reports whether the additional service must be contracted.
	// Mandatory ones must not be sent in ConfirmService.
	Mandatory FlexBool `json:"obligatorio"`
	// Collection reports whether the additional service is a collection
	// (cash on delivery) type. There may be more than one collection
	// service varying by coverage, but only one per condition is returned.
	Collection FlexBool `json:"cobranza"`
	// Preselected reports whether the service is selected by default for
	// the service type. When false, its cost should not be counted toward
	// the total freight.
	Preselected FlexBool `json:"preseleccionado"`
	// Value is the amount the cost was calculated on.
	Value FlexFloat `json:"valor"`
	// Return contains return shipment information, or is null when the
	// additional service does not generate a return shipment.
	Return *ReturnShipment `json:"devolucion"`
}

// ServiceCondition is one service available for a requested shipment, as
// returned by RequestService. The chosen condition feeds ConfirmService.
type ServiceCondition struct {
	// ServiceTypeID is the AEX service identifier.
	ServiceTypeID FlexInt `json:"id_tipo_servicio"`
	// ServiceType is the service type name.
	ServiceType string `json:"tipo_servicio"`
	// Description is the detailed service description.
	Description string `json:"descripcion"`
	// IncludesPickup reports whether the service requires pickup; when
	// false the client leaves packages at a delivery point.
	IncludesPickup TFBool `json:"incluye_pickup"`
	// IncludesDelivery reports whether the service requires delivery; when
	// false the client picks packages up at a delivery point.
	IncludesDelivery TFBool `json:"incluye_envio"`
	// FreightCost is the freight cost in guaraníes.
	FreightCost FlexFloat `json:"costo_flete"`
	// AdditionalServices lists extra services to freight (e.g.,
	// insurance).
	AdditionalServices []ConditionAdditional `json:"adicionales"`
	// DeliveryTime is the estimated maximum delivery time in hours,
	// counted from cargo pickup.
	DeliveryTime FlexInt `json:"tiempo_entrega"`
	// DeliveryPoints lists the points available for package delivery.
	DeliveryPoints []DeliveryPoint `json:"puntos_entrega"`
}

// ServiceOffer is the offer generated by RequestService: an identifier to
// use when confirming, plus the conditions available for the shipment.
type ServiceOffer struct {
	// ID is the service offer identifier (id_solicitud) to pass to
	// ConfirmService.
	ID FlexInt `json:"id_solicitud"`
	// Conditions lists the available services for the shipment.
	Conditions []ServiceCondition `json:"condiciones"`
}

// serviceOfferResponse is the wire response of RequestService. The
// documentation is ambiguous about whether datos holds the offer object or
// a one-element array; decodeServiceOffer tolerates both.
type serviceOfferResponse struct {
	baseResponse
	Datos json.RawMessage `json:"datos"`
}

func decodeServiceOffer(raw json.RawMessage) (ServiceOffer, error) {
	trimmed := string(raw)
	if trimmed == "" || trimmed == "null" {
		return ServiceOffer{}, fmt.Errorf("aex: request service: response carried no service offer")
	}

	var offer ServiceOffer
	if err := json.Unmarshal(raw, &offer); err == nil && offer.ID != 0 {
		return offer, nil
	}

	var offers []ServiceOffer
	if err := json.Unmarshal(raw, &offers); err == nil && len(offers) > 0 {
		return offers[0], nil
	}
	return ServiceOffer{}, fmt.Errorf("aex: request service: cannot decode service offer from %s", trimmed)
}

// RequestService generates a service offer for the given origin,
// destination, and packages. Confirm the returned offer with
// ConfirmService before it expires.
func (c *Client) RequestService(ctx context.Context, params RequestServiceParams) (ServiceOffer, error) {
	if err := params.validate(); err != nil {
		return ServiceOffer{}, err
	}

	var resp serviceOfferResponse
	if err := c.doAuthenticated(ctx, requestServicePath, &params, &resp); err != nil {
		return ServiceOffer{}, err
	}
	return decodeServiceOffer(resp.Datos)
}
